# Lab 4

Import the neccesary libraries

In [1]:
import pandas as pd
import numpy as np
from IPython.display import Image
np.set_printoptions(precision = 3)

Load the data

In [2]:
data = pd.read_csv("jester-data-1.csv",header = None)
# Erase the first column, which indicate the users
data = data.drop(columns=[0])
data.head()

1      2      3      4     5     6     7     8      9      10   ...    \
0  -7.82   8.79  -9.66  -8.16 -7.52 -8.50 -9.85  4.17  -8.98  -4.76  ...     
1   4.08  -0.29   6.36   4.37 -2.38 -9.66 -0.73 -5.34   8.88   9.22  ...     
2  99.00  99.00  99.00  99.00  9.03  9.27  9.03  9.27  99.00  99.00  ...     
3  99.00   8.35  99.00  99.00  1.80  8.16 -2.82  6.21  99.00   1.84  ...     
4   8.50   4.61  -4.17  -5.39  1.36  1.60  7.04  4.61  -0.44   5.73  ...     

     91     92     93     94     95     96     97     98     99     100  
0   2.82  99.00  99.00  99.00  99.00  99.00  -5.63  99.00  99.00  99.00  
1   2.82  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
2  99.00  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
3  99.00  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
4   5.19   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  

[5 rows x 100 columns]

Copy the original data for a back up

In [3]:
# we save a copy of the previous data
old_data = data.copy()
old_data.head()

1      2      3      4     5     6     7     8      9      10   ...    \
0  -7.82   8.79  -9.66  -8.16 -7.52 -8.50 -9.85  4.17  -8.98  -4.76  ...     
1   4.08  -0.29   6.36   4.37 -2.38 -9.66 -0.73 -5.34   8.88   9.22  ...     
2  99.00  99.00  99.00  99.00  9.03  9.27  9.03  9.27  99.00  99.00  ...     
3  99.00   8.35  99.00  99.00  1.80  8.16 -2.82  6.21  99.00   1.84  ...     
4   8.50   4.61  -4.17  -5.39  1.36  1.60  7.04  4.61  -0.44   5.73  ...     

     91     92     93     94     95     96     97     98     99     100  
0   2.82  99.00  99.00  99.00  99.00  99.00  -5.63  99.00  99.00  99.00  
1   2.82  -4.95  -0.29   7.86  -0.19  -2.14   3.06   0.34  -4.32   1.07  
2  99.00  99.00  99.00   9.08  99.00  99.00  99.00  99.00  99.00  99.00  
3  99.00  99.00  99.00   0.53  99.00  99.00  99.00  99.00  99.00  99.00  
4   5.19   5.58   4.27   5.19   5.73   1.55   3.11   6.55   1.80   1.60  

[5 rows x 100 columns]

Select one part of the data to work on

In [4]:
# We select only 120 rows for practicing, a larger amount may create an overflow according to the user's computer
old_short_data = old_data [:120].copy()
old_short_data = old_short_data.values
new_data = data [:120].copy()
new_data = new_data.values

In [5]:
print(new_data)

[[-7.82  8.79 -9.66 ... 99.   99.   99.  ]
 [ 4.08 -0.29  6.36 ...  0.34 -4.32  1.07]
 [99.   99.   99.   ... 99.   99.   99.  ]
 ...
 [ 4.22  4.22 -3.59 ... 99.   99.   99.  ]
 [ 8.93  8.93  5.24 ... -8.59  0.53  7.28]
 [ 5.29  6.6  99.   ... 99.   99.   99.  ]]


Modify the data, so 10% has 99 as value

In [6]:
amount = 252318
a =0
count = 0
for i in range(0,100):
        for j in range(0,120):
            a = a + 1
            if count < amount:
                if a == 7:
                    a = 0
                    new_data[j][i] = 99
print(new_data)

[[-7.82  8.79 -9.66 ... 99.   99.   99.  ]
 [ 4.08 -0.29  6.36 ...  0.34 -4.32  1.07]
 [99.   99.   99.   ... 99.   99.   99.  ]
 ...
 [ 4.22 99.   -3.59 ... 99.   99.   99.  ]
 [99.    8.93  5.24 ... -8.59 99.    7.28]
 [ 5.29  6.6  99.   ... 99.   99.   99.  ]]


Prepare information for the training

In [7]:
#d_new = new_data.to_latex()
n_features = 2

user_ratings = new_data
latent_user_preferences = np.random.random((user_ratings.shape[0], n_features))
latent_item_features = np.random.random((user_ratings.shape[1],n_features))

Prediction, training and testing. Showing the MSE

In [8]:
def predict_rating(user_id,item_id):
    """ Predict a rating given a user_id and an item_id.
    """
    user_preference = latent_user_preferences[user_id]
    item_preference = latent_item_features[item_id]
    return user_preference.dot(item_preference)

def train(user_id, item_id, rating,alpha = 0.001):
    prediction_rating = predict_rating(user_id, item_id)
    err =  ( prediction_rating - rating );
    user_pref_values = latent_user_preferences[user_id][:]
    latent_user_preferences[user_id] -= alpha * err * latent_item_features[item_id]
    latent_item_features[item_id] -= alpha * err * user_pref_values
    return err

def test(user_id, item_id, rating,alpha = 0.001):
    prediction_rating = predict_rating(user_id, item_id)
    err_test =  ( prediction_rating - rating );
    return err_test



def sgd(iterations = 3000):
    """ Iterate over all users and all items and train for 
        a certain number of iterations
    """
    for iteration in range(0,iterations):
        error = []
        error_test=[]
        for user_id in range(0,latent_user_preferences.shape[0]):
            for item_id in range(0,latent_item_features.shape[0]):
                rating = user_ratings[user_id][item_id]
                rating_test = old_short_data[user_id][item_id]
                # We check if the value is not 99
                if(rating != 99 ):
                    err = train(user_id,item_id,rating)
                    error.append(err)
                if(rating_test != 99 ):
                    err_test = test(user_id,item_id,rating_test)
                    error_test.append(err_test)
        mse = (np.array(error) ** 2).mean()
        mse_test = (np.array(error_test) ** 2).mean()
        if(iteration%100 == 0 ):
            print ("mse in the train iteration",iteration,"is",mse)
            print ("mse in the test iteration",iteration,"is",mse_test)
    print("Final train mse", mse)
    print("Final test mse", mse_test)

In [9]:
sgd()

mse in the train iteration 0 is 27.37295004112655
mse in the test iteration 0 is 27.1894614096285
mse in the train iteration 100 is 17.073440237622254
mse in the test iteration 100 is 17.006565004449136
mse in the train iteration 200 is 17.073321875188732
mse in the test iteration 200 is 17.0071701319018
mse in the train iteration 300 is 17.078588239218316
mse in the test iteration 300 is 17.00191930457554
mse in the train iteration 400 is 17.085931961439027
mse in the test iteration 400 is 16.99424462741476
mse in the train iteration 500 is 17.09550033776797
mse in the test iteration 500 is 16.984283365031914
mse in the train iteration 600 is 17.10743847118059
mse in the test iteration 600 is 16.97185645924079
mse in the train iteration 700 is 17.121914670026033
mse in the test iteration 700 is 16.956718220786538
mse in the train iteration 800 is 17.139124729911124
mse in the test iteration 800 is 16.938568045999098
mse in the train iteration 900 is 17.159293249030785
mse in the test 

Show the Predictions

In [10]:
predictions = latent_user_preferences.dot(latent_item_features.T)
predictions

array([[-2.717, -1.137, -2.986, ...,  0.787, -2.899,  2.461],
       [ 2.2  ,  1.556,  2.258, ...,  0.293,  2.218, -0.033],
       [ 7.334,  6.191,  7.275, ...,  2.446,  7.186,  2.99 ],
       ...,
       [-0.415, -0.216, -0.445, ...,  0.058, -0.434,  0.245],
       [ 0.719,  1.018,  0.61 , ...,  0.842,  0.62 ,  1.562],
       [ 0.894,  1.941,  0.589, ...,  2.034,  0.634,  4.022]])

Create a comparation of the predcitions and the actual data

In [11]:
values = [zip(old_short_data[i], predictions[i]) for i in range(0,predictions.shape[0])]
comparison_data = pd.DataFrame(values)
comparison_data.columns = old_data.columns
#comparison_data.applymap(lambda (x,y): "(%2.3f|%2.3f)"%(x,y))

In [12]:
comparison_data

1                              2    \
0     (-7.82, -2.717435055404733)     (8.79, -1.136540652082711)   
1        (4.08, 2.20034304741583)    (-0.29, 1.5557831452325164)   
2       (99.0, 7.334103675300317)      (99.0, 6.191163791615592)   
3      (99.0, 0.9446094286413608)     (8.35, 1.0602672006008025)   
4        (8.5, 3.578706821172213)      (4.61, 3.358219295724386)   
5     (-6.17, -4.196214321344237)    (-3.54, -3.578129160155699)   
6       (99.0, 4.057203977985465)      (99.0, 3.838895332300753)   
7     (6.84, -2.6458383448552447)    (3.16, -1.7669048022920506)   
8    (-3.79, -0.5704778426189976)   (-3.54, 0.12612115138741314)   
9       (3.01, 3.610171690594961)      (5.15, 3.225544473768591)   
10    (-2.91, 3.7785882898858785)      (4.08, 3.786879682006354)   
11     (1.31, 1.6726490029863255)      (1.8, 2.0051026795338425)   
12     (99.0, 5.1137785360770724)      (99.0, 4.968548787322851)   
13      (9.22, 4.435932412710736)      (9.27, 4.527593893045447)   
14   (8.79, -0.05818247456608684)  (-5.78, -0.44257969719543255)   
15    (-3.5, -0.7175118042783291)     (1.55, 0.1945738439349049)   
16     (99.0, 2.1766173257982264)    (-9.27, 2.4587841260975565)   
17     (3.16, 4.2245117047254555)      (7.62, 4.027845881759905)   
18     (4.22, 1.0209526196841083)     (3.64, 0.5475229976987299)   
19     (99.0, -0.934655723662993)   (7.62, 0.004001255966532629)   
20    (2.57, -0.5953179976175826)  (-0.73, -0.13403203791363455)   
21     (7.28, 0.5137266716399121)    (5.39, 0.42203192575287685)   
22     (2.72, 1.6819749113576539)      (4.17, 2.019770473572041)   
23      (2.09, 4.207496910477603)     (-7.57, 4.256110848955276)   
24    (-3.93, 1.0701405647190634)    (-1.17, 1.2046527830321987)   
25     (99.0, 2.5229145251581855)     (5.49, 2.5710574915744164)   
26     (99.0, 1.4373248895029471)      (5.83, 1.497621530877181)   
27    (0.49, -1.9044930968628924)    (0.15, -0.8424895249333361)   
28     (99.0, 1.0583011238477127)     (99.0, 1.9789231916500691)   
29     (99.0, 2.4842460754177536)      (4.08, 2.246320219959021)   
..                            ...                            ...   
90    (-3.16, 1.9624906825506463)    (-1.12, 1.6927618486827671)   
91     (99.0, 1.6283250800074671)     (-5.83, 2.313578442965228)   
92    (99.0, -0.8678737384388473)    (99.0, -0.5285370774022323)   
93      (-1.26, 3.63294742189016)     (6.02, 3.2576674733070403)   
94      (8.16, 4.628890816197035)     (2.28, 3.8821187273244604)   
95    (0.44, 0.14967696868814187)   (-8.45, 0.24366276133082715)   
96    (3.54, 0.27603707714179576)     (-5.0, 1.1295572091752026)   
97    (99.0, 0.14425407537295262)    (99.0, -0.2076016974505893)   
98      (3.3, 2.0263633542105053)     (1.31, 2.0404665013898535)   
99    (99.0, -2.2429548658860523)    (99.0, -1.7994787625548752)   
100     (99.0, 3.110330903746464)     (-8.5, 3.2708325572724997)   
101   (6.17, -0.1888802462528825)    (7.77, 0.20572957604317743)   
102   (5.68, -1.1208057778310598)   (-2.86, -0.9308226940513301)   
103  (-1.89, -3.4700683995938473)    (-2.77, -2.982585408183089)   
104   (-0.92, -4.238135256842741)    (-7.82, -3.783482852757598)   
105    (99.0, 0.6162620158898966)    (-0.73, 1.9822961767586673)   
106   (3.45, -1.1938917187522613)   (-2.86, -0.6456580472192037)   
107  (-2.18, -1.1291530544793429)   (-4.56, -0.7708305812924803)   
108    (5.39, 1.8451147784789543)    (-2.57, 1.6797355727929855)   
109     (3.11, 5.901446194068204)     (-2.77, 4.896507878223147)   
110   (3.06, -0.7420468890106908)    (0.87, -0.2386355536974824)   
111     (99.0, 4.653844386623396)      (5.73, 4.520022644946663)   
112   (2.38, -1.1513796558808775)    (1.65, -1.2403960432294268)   
113    (99.0, -0.848481873688544)    (99.0, 0.12525462315352695)   
114    (4.61, 1.6069698326789097)       (1.6, 2.019865688089709)   
115   (-5.0, -1.5449749527931018)   (8.83, -0.41719520808767974)   
116    (99.0, 1.0246879254976191)     (99.0, 1.1685397337916745)   
117  (4.22, -0.414